-- impulso_previne_dados_nominais.painel_vacinacao_lista_nominal source

CREATE MATERIALIZED VIEW impulso_previne_dados_nominais.painel_vacinacao_lista_nominal
TABLESPACE pg_default
AS WITH dados_anonimizados_demo_vicosa AS (
         SELECT res.chave_cidadao,
            upper(nomes.nome_ficticio) AS cidadao_nome,
            res.cidadao_cpf,
            res.cidadao_cns,
            res.dt_nascimento,
            res.cidadao_idade_meses_atual,
            res.status_idade,
            res.quadrimestre_completa_1_ano,
            res.data_1dose_polio,
            res.data_2dose_polio,
            res.data_3dose_polio,
            res.qtde_vacinas_polio_registradas,
            res.quantidade_polio_validas,
            res.idade_meses_1dose_polio,
            res.idade_meses_2dose_polio,
            res.idade_meses_3dose_polio,
            res.prazo_1dose_polio,
            res.prazo_limite_1dose_polio,
            res.prazo_2dose_polio,
            res.prazo_3dose_polio,
            res.data_1dose_penta,
            res.data_2dose_penta,
            res.data_3dose_penta,
            res.qtde_vacinas_penta_registradas,
            res.quantidade_penta_validas,
            res.idade_meses_1dose_penta,
            res.idade_meses_2dose_penta,
            res.idade_meses_3dose_penta,
            res.prazo_1dose_penta,
            res.prazo_limite_1dose_penta,
            res.prazo_2dose_penta,
            res.prazo_3dose_penta,
            res.cidadao_nome_responsavel,
            res.estabelecimento_cnes_atendimento,
            res.estabelecimento_cnes_cadastro,
            res.estabelecimento_nome_atendimento,
            res.estabelecimento_nome_cadastro,
            res.equipe_ine_atendimento,
            res.equipe_ine_cadastro,
            res.equipe_nome_atendimento,
            res.equipe_nome_cadastro,
            upper(nomes2.nome_ficticio) AS acs_nome_cadastro,
            upper(nomes2.nome_ficticio) AS acs_nome_visita,
            res.data_ultimo_cadastro_individual,
            res.data_ultimo_atendimento_individual,
            res.data_ultima_vista_domiciliar,
            res.criacao_data,
            '100111'::character varying AS municipio_id_sus,
            res.quadrimestre_atual
           FROM ( SELECT row_number() OVER (PARTITION BY 0::integer) AS seq,
                    lista_nominal_vacinacao.chave_cidadao,
                    lista_nominal_vacinacao.cidadao_nome,
                    concat(impulso_previne_dados_nominais.random_between(100000000, 999999999)::text, impulso_previne_dados_nominais.random_between(10, 99)::text) AS cidadao_cpf,
                    concat('7', impulso_previne_dados_nominais.random_between(100000000, 999999999)::text, impulso_previne_dados_nominais.random_between(10000, 99999)::text) AS cidadao_cns,
                    lista_nominal_vacinacao.dt_nascimento,
                    lista_nominal_vacinacao.cidadao_idade_meses_atual,
                    lista_nominal_vacinacao.status_idade,
                    lista_nominal_vacinacao.quadrimestre_completa_1_ano,
                    lista_nominal_vacinacao.data_1dose_polio,
                    lista_nominal_vacinacao.data_2dose_polio,
                    lista_nominal_vacinacao.data_3dose_polio,
                    lista_nominal_vacinacao.qtde_vacinas_polio_registradas,
                    lista_nominal_vacinacao.quantidade_polio_validas,
                    lista_nominal_vacinacao.idade_meses_1dose_polio,
                    lista_nominal_vacinacao.idade_meses_2dose_polio,
                    lista_nominal_vacinacao.idade_meses_3dose_polio,
                    lista_nominal_vacinacao.prazo_1dose_polio,
                    lista_nominal_vacinacao.prazo_limite_1dose_polio,
                    lista_nominal_vacinacao.prazo_2dose_polio,
                    lista_nominal_vacinacao.prazo_3dose_polio,
                    lista_nominal_vacinacao.data_1dose_penta,
                    lista_nominal_vacinacao.data_2dose_penta,
                    lista_nominal_vacinacao.data_3dose_penta,
                    lista_nominal_vacinacao.qtde_vacinas_penta_registradas,
                    lista_nominal_vacinacao.quantidade_penta_validas,
                    lista_nominal_vacinacao.idade_meses_1dose_penta,
                    lista_nominal_vacinacao.idade_meses_2dose_penta,
                    lista_nominal_vacinacao.idade_meses_3dose_penta,
                    lista_nominal_vacinacao.prazo_1dose_penta,
                    lista_nominal_vacinacao.prazo_limite_1dose_penta,
                    lista_nominal_vacinacao.prazo_2dose_penta,
                    lista_nominal_vacinacao.prazo_3dose_penta,
                    lista_nominal_vacinacao.cidadao_nome_responsavel,
                    lista_nominal_vacinacao.estabelecimento_cnes_atendimento,
                    lista_nominal_vacinacao.estabelecimento_cnes_cadastro,
                    lista_nominal_vacinacao.estabelecimento_nome_atendimento,
                    lista_nominal_vacinacao.estabelecimento_nome_cadastro,
                    lista_nominal_vacinacao.equipe_ine_atendimento,
                    lista_nominal_vacinacao.equipe_ine_cadastro,
                    lista_nominal_vacinacao.equipe_nome_atendimento,
                    lista_nominal_vacinacao.equipe_nome_cadastro,
                    lista_nominal_vacinacao.acs_nome_cadastro,
                    lista_nominal_vacinacao.acs_nome_visita,
                    lista_nominal_vacinacao.data_ultimo_cadastro_individual,
                    lista_nominal_vacinacao.data_ultimo_atendimento_individual,
                    lista_nominal_vacinacao.data_ultima_vista_domiciliar,
                    lista_nominal_vacinacao.criacao_data,
                    lista_nominal_vacinacao.quadrimestre_atual
                   FROM impulso_previne_dados_nominais.lista_nominal_vacinacao_unificada lista_nominal_vacinacao
                  WHERE lista_nominal_vacinacao.municipio_id_sus::text = '317130'::text) res
             JOIN configuracoes.nomes_ficticios_vacinacao nomes ON res.seq = nomes.seq
             JOIN configuracoes.nomes_ficticios_diabeticos nomes2 ON res.seq = nomes2.seq
        ), dados_anonimizados_impulsolandia AS (
         SELECT res.chave_cidadao,
            upper(nomes.nome_ficticio) AS cidadao_nome,
            res.cidadao_cpf,
            res.cidadao_cns,
            res.dt_nascimento,
            res.cidadao_idade_meses_atual,
            res.status_idade,
            res.quadrimestre_completa_1_ano,
            res.data_1dose_polio,
            res.data_2dose_polio,
            res.data_3dose_polio,
            res.qtde_vacinas_polio_registradas,
            res.quantidade_polio_validas,
            res.idade_meses_1dose_polio,
            res.idade_meses_2dose_polio,
            res.idade_meses_3dose_polio,
            res.prazo_1dose_polio,
            res.prazo_limite_1dose_polio,
            res.prazo_2dose_polio,
            res.prazo_3dose_polio,
            res.data_1dose_penta,
            res.data_2dose_penta,
            res.data_3dose_penta,
            res.qtde_vacinas_penta_registradas,
            res.quantidade_penta_validas,
            res.idade_meses_1dose_penta,
            res.idade_meses_2dose_penta,
            res.idade_meses_3dose_penta,
            res.prazo_1dose_penta,
            res.prazo_limite_1dose_penta,
            res.prazo_2dose_penta,
            res.prazo_3dose_penta,
            res.cidadao_nome_responsavel,
            res.estabelecimento_cnes_atendimento,
            res.estabelecimento_cnes_cadastro,
            res.estabelecimento_nome_atendimento,
            res.estabelecimento_nome_cadastro,
            res.equipe_ine_atendimento,
            res.equipe_ine_cadastro,
            res.equipe_nome_atendimento,
            res.equipe_nome_cadastro,
            upper(nomes2.nome_ficticio) AS acs_nome_cadastro,
            upper(nomes2.nome_ficticio) AS acs_nome_visita,
            res.data_ultimo_cadastro_individual,
            res.data_ultimo_atendimento_individual,
            res.data_ultima_vista_domiciliar,
            res.criacao_data,
            '111111'::character varying AS municipio_id_sus,
            res.quadrimestre_atual
           FROM ( SELECT row_number() OVER (PARTITION BY 0::integer) AS seq,
                    lista_nominal_vacinacao.chave_cidadao,
                    lista_nominal_vacinacao.cidadao_nome,
                    concat(impulso_previne_dados_nominais.random_between(100000000, 999999999)::text, impulso_previne_dados_nominais.random_between(10, 99)::text) AS cidadao_cpf,
                    concat('7', impulso_previne_dados_nominais.random_between(100000000, 999999999)::text, impulso_previne_dados_nominais.random_between(10000, 99999)::text) AS cidadao_cns,
                    lista_nominal_vacinacao.dt_nascimento,
                    lista_nominal_vacinacao.cidadao_idade_meses_atual,
                    lista_nominal_vacinacao.status_idade,
                    lista_nominal_vacinacao.quadrimestre_completa_1_ano,
                    lista_nominal_vacinacao.data_1dose_polio,
                    lista_nominal_vacinacao.data_2dose_polio,
                    lista_nominal_vacinacao.data_3dose_polio,
                    lista_nominal_vacinacao.qtde_vacinas_polio_registradas,
                    lista_nominal_vacinacao.quantidade_polio_validas,
                    lista_nominal_vacinacao.idade_meses_1dose_polio,
                    lista_nominal_vacinacao.idade_meses_2dose_polio,
                    lista_nominal_vacinacao.idade_meses_3dose_polio,
                    lista_nominal_vacinacao.prazo_1dose_polio,
                    lista_nominal_vacinacao.prazo_limite_1dose_polio,
                    lista_nominal_vacinacao.prazo_2dose_polio,
                    lista_nominal_vacinacao.prazo_3dose_polio,
                    lista_nominal_vacinacao.data_1dose_penta,
                    lista_nominal_vacinacao.data_2dose_penta,
                    lista_nominal_vacinacao.data_3dose_penta,
                    lista_nominal_vacinacao.qtde_vacinas_penta_registradas,
                    lista_nominal_vacinacao.quantidade_penta_validas,
                    lista_nominal_vacinacao.idade_meses_1dose_penta,
                    lista_nominal_vacinacao.idade_meses_2dose_penta,
                    lista_nominal_vacinacao.idade_meses_3dose_penta,
                    lista_nominal_vacinacao.prazo_1dose_penta,
                    lista_nominal_vacinacao.prazo_limite_1dose_penta,
                    lista_nominal_vacinacao.prazo_2dose_penta,
                    lista_nominal_vacinacao.prazo_3dose_penta,
                    lista_nominal_vacinacao.cidadao_nome_responsavel,
                    lista_nominal_vacinacao.estabelecimento_cnes_atendimento,
                    lista_nominal_vacinacao.estabelecimento_cnes_cadastro,
                    lista_nominal_vacinacao.estabelecimento_nome_atendimento,
                    lista_nominal_vacinacao.estabelecimento_nome_cadastro,
                    lista_nominal_vacinacao.equipe_ine_atendimento,
                    lista_nominal_vacinacao.equipe_ine_cadastro,
                    lista_nominal_vacinacao.equipe_nome_atendimento,
                    lista_nominal_vacinacao.equipe_nome_cadastro,
                    lista_nominal_vacinacao.acs_nome_cadastro,
                    lista_nominal_vacinacao.acs_nome_visita,
                    lista_nominal_vacinacao.data_ultimo_cadastro_individual,
                    lista_nominal_vacinacao.data_ultimo_atendimento_individual,
                    lista_nominal_vacinacao.data_ultima_vista_domiciliar,
                    lista_nominal_vacinacao.criacao_data,
                    lista_nominal_vacinacao.quadrimestre_atual
                   FROM impulso_previne_dados_nominais.lista_nominal_vacinacao_unificada lista_nominal_vacinacao
                  WHERE lista_nominal_vacinacao.municipio_id_sus::text = '317130'::text) res
             JOIN configuracoes.nomes_ficticios_vacinacao nomes ON res.seq = nomes.seq
             JOIN configuracoes.nomes_ficticios_diabeticos nomes2 ON res.seq = nomes2.seq
        ), dados_transmissoes_recentes AS (
         SELECT tb1_1.chave_cidadao,
            tb1_1.cidadao_nome,
            tb1_1.cidadao_cpf,
            tb1_1.cidadao_cns,
            tb1_1.dt_nascimento,
            tb1_1.cidadao_idade_meses_atual,
            tb1_1.status_idade,
            tb1_1.quadrimestre_completa_1_ano,
            tb1_1.data_1dose_polio,
            tb1_1.data_2dose_polio,
            tb1_1.data_3dose_polio,
            tb1_1.qtde_vacinas_polio_registradas,
            tb1_1.quantidade_polio_validas,
            tb1_1.idade_meses_1dose_polio,
            tb1_1.idade_meses_2dose_polio,
            tb1_1.idade_meses_3dose_polio,
            tb1_1.prazo_1dose_polio,
            tb1_1.prazo_limite_1dose_polio,
            tb1_1.prazo_2dose_polio,
            tb1_1.prazo_3dose_polio,
            tb1_1.data_1dose_penta,
            tb1_1.data_2dose_penta,
            tb1_1.data_3dose_penta,
            tb1_1.qtde_vacinas_penta_registradas,
            tb1_1.quantidade_penta_validas,
            tb1_1.idade_meses_1dose_penta,
            tb1_1.idade_meses_2dose_penta,
            tb1_1.idade_meses_3dose_penta,
            tb1_1.prazo_1dose_penta,
            tb1_1.prazo_limite_1dose_penta,
            tb1_1.prazo_2dose_penta,
            tb1_1.prazo_3dose_penta,
            tb1_1.cidadao_nome_responsavel,
            tb1_1.estabelecimento_cnes_atendimento,
            tb1_1.estabelecimento_cnes_cadastro,
            tb1_1.estabelecimento_nome_atendimento,
            tb1_1.estabelecimento_nome_cadastro,
            tb1_1.equipe_ine_atendimento,
            tb1_1.equipe_ine_cadastro,
            tb1_1.equipe_nome_atendimento,
            tb1_1.equipe_nome_cadastro,
            tb1_1.acs_nome_cadastro,
            tb1_1.acs_nome_visita,
            tb1_1.data_ultimo_cadastro_individual,
            tb1_1.data_ultimo_atendimento_individual,
            tb1_1.data_ultima_vista_domiciliar,
            tb1_1.criacao_data,
            tb1_1.municipio_id_sus,
            tb1_1.quadrimestre_atual
           FROM impulso_previne_dados_nominais.lista_nominal_vacinacao_unificada tb1_1
        ), une_as_bases AS (
         SELECT dados_anonimizados_demo_vicosa.chave_cidadao,
            dados_anonimizados_demo_vicosa.cidadao_nome,
            dados_anonimizados_demo_vicosa.cidadao_cpf,
            dados_anonimizados_demo_vicosa.cidadao_cns,
            dados_anonimizados_demo_vicosa.dt_nascimento,
            dados_anonimizados_demo_vicosa.cidadao_idade_meses_atual,
            dados_anonimizados_demo_vicosa.status_idade,
            dados_anonimizados_demo_vicosa.quadrimestre_completa_1_ano,
            dados_anonimizados_demo_vicosa.data_1dose_polio,
            dados_anonimizados_demo_vicosa.data_2dose_polio,
            dados_anonimizados_demo_vicosa.data_3dose_polio,
            dados_anonimizados_demo_vicosa.qtde_vacinas_polio_registradas,
            dados_anonimizados_demo_vicosa.quantidade_polio_validas,
            dados_anonimizados_demo_vicosa.idade_meses_1dose_polio,
            dados_anonimizados_demo_vicosa.idade_meses_2dose_polio,
            dados_anonimizados_demo_vicosa.idade_meses_3dose_polio,
            dados_anonimizados_demo_vicosa.prazo_1dose_polio,
            dados_anonimizados_demo_vicosa.prazo_limite_1dose_polio,
            dados_anonimizados_demo_vicosa.prazo_2dose_polio,
            dados_anonimizados_demo_vicosa.prazo_3dose_polio,
            dados_anonimizados_demo_vicosa.data_1dose_penta,
            dados_anonimizados_demo_vicosa.data_2dose_penta,
            dados_anonimizados_demo_vicosa.data_3dose_penta,
            dados_anonimizados_demo_vicosa.qtde_vacinas_penta_registradas,
            dados_anonimizados_demo_vicosa.quantidade_penta_validas,
            dados_anonimizados_demo_vicosa.idade_meses_1dose_penta,
            dados_anonimizados_demo_vicosa.idade_meses_2dose_penta,
            dados_anonimizados_demo_vicosa.idade_meses_3dose_penta,
            dados_anonimizados_demo_vicosa.prazo_1dose_penta,
            dados_anonimizados_demo_vicosa.prazo_limite_1dose_penta,
            dados_anonimizados_demo_vicosa.prazo_2dose_penta,
            dados_anonimizados_demo_vicosa.prazo_3dose_penta,
            dados_anonimizados_demo_vicosa.cidadao_nome_responsavel,
            dados_anonimizados_demo_vicosa.estabelecimento_cnes_atendimento,
            dados_anonimizados_demo_vicosa.estabelecimento_cnes_cadastro,
            dados_anonimizados_demo_vicosa.estabelecimento_nome_atendimento,
            dados_anonimizados_demo_vicosa.estabelecimento_nome_cadastro,
            dados_anonimizados_demo_vicosa.equipe_ine_atendimento,
            dados_anonimizados_demo_vicosa.equipe_ine_cadastro,
            dados_anonimizados_demo_vicosa.equipe_nome_atendimento,
            dados_anonimizados_demo_vicosa.equipe_nome_cadastro,
            dados_anonimizados_demo_vicosa.acs_nome_cadastro,
            dados_anonimizados_demo_vicosa.acs_nome_visita,
            dados_anonimizados_demo_vicosa.data_ultimo_cadastro_individual,
            dados_anonimizados_demo_vicosa.data_ultimo_atendimento_individual,
            dados_anonimizados_demo_vicosa.data_ultima_vista_domiciliar,
            dados_anonimizados_demo_vicosa.criacao_data,
            dados_anonimizados_demo_vicosa.municipio_id_sus,
            dados_anonimizados_demo_vicosa.quadrimestre_atual
           FROM dados_anonimizados_demo_vicosa
        UNION ALL
         SELECT dados_anonimizados_impulsolandia.chave_cidadao,
            dados_anonimizados_impulsolandia.cidadao_nome,
            dados_anonimizados_impulsolandia.cidadao_cpf,
            dados_anonimizados_impulsolandia.cidadao_cns,
            dados_anonimizados_impulsolandia.dt_nascimento,
            dados_anonimizados_impulsolandia.cidadao_idade_meses_atual,
            dados_anonimizados_impulsolandia.status_idade,
            dados_anonimizados_impulsolandia.quadrimestre_completa_1_ano,
            dados_anonimizados_impulsolandia.data_1dose_polio,
            dados_anonimizados_impulsolandia.data_2dose_polio,
            dados_anonimizados_impulsolandia.data_3dose_polio,
            dados_anonimizados_impulsolandia.qtde_vacinas_polio_registradas,
            dados_anonimizados_impulsolandia.quantidade_polio_validas,
            dados_anonimizados_impulsolandia.idade_meses_1dose_polio,
            dados_anonimizados_impulsolandia.idade_meses_2dose_polio,
            dados_anonimizados_impulsolandia.idade_meses_3dose_polio,
            dados_anonimizados_impulsolandia.prazo_1dose_polio,
            dados_anonimizados_impulsolandia.prazo_limite_1dose_polio,
            dados_anonimizados_impulsolandia.prazo_2dose_polio,
            dados_anonimizados_impulsolandia.prazo_3dose_polio,
            dados_anonimizados_impulsolandia.data_1dose_penta,
            dados_anonimizados_impulsolandia.data_2dose_penta,
            dados_anonimizados_impulsolandia.data_3dose_penta,
            dados_anonimizados_impulsolandia.qtde_vacinas_penta_registradas,
            dados_anonimizados_impulsolandia.quantidade_penta_validas,
            dados_anonimizados_impulsolandia.idade_meses_1dose_penta,
            dados_anonimizados_impulsolandia.idade_meses_2dose_penta,
            dados_anonimizados_impulsolandia.idade_meses_3dose_penta,
            dados_anonimizados_impulsolandia.prazo_1dose_penta,
            dados_anonimizados_impulsolandia.prazo_limite_1dose_penta,
            dados_anonimizados_impulsolandia.prazo_2dose_penta,
            dados_anonimizados_impulsolandia.prazo_3dose_penta,
            dados_anonimizados_impulsolandia.cidadao_nome_responsavel,
            dados_anonimizados_impulsolandia.estabelecimento_cnes_atendimento,
            dados_anonimizados_impulsolandia.estabelecimento_cnes_cadastro,
            dados_anonimizados_impulsolandia.estabelecimento_nome_atendimento,
            dados_anonimizados_impulsolandia.estabelecimento_nome_cadastro,
            dados_anonimizados_impulsolandia.equipe_ine_atendimento,
            dados_anonimizados_impulsolandia.equipe_ine_cadastro,
            dados_anonimizados_impulsolandia.equipe_nome_atendimento,
            dados_anonimizados_impulsolandia.equipe_nome_cadastro,
            dados_anonimizados_impulsolandia.acs_nome_cadastro,
            dados_anonimizados_impulsolandia.acs_nome_visita,
            dados_anonimizados_impulsolandia.data_ultimo_cadastro_individual,
            dados_anonimizados_impulsolandia.data_ultimo_atendimento_individual,
            dados_anonimizados_impulsolandia.data_ultima_vista_domiciliar,
            dados_anonimizados_impulsolandia.criacao_data,
            dados_anonimizados_impulsolandia.municipio_id_sus,
            dados_anonimizados_impulsolandia.quadrimestre_atual
           FROM dados_anonimizados_impulsolandia
        UNION ALL
         SELECT dados_transmissoes_recentes.chave_cidadao,
            dados_transmissoes_recentes.cidadao_nome,
            dados_transmissoes_recentes.cidadao_cpf,
            dados_transmissoes_recentes.cidadao_cns,
            dados_transmissoes_recentes.dt_nascimento,
            dados_transmissoes_recentes.cidadao_idade_meses_atual,
            dados_transmissoes_recentes.status_idade,
            dados_transmissoes_recentes.quadrimestre_completa_1_ano,
            dados_transmissoes_recentes.data_1dose_polio,
            dados_transmissoes_recentes.data_2dose_polio,
            dados_transmissoes_recentes.data_3dose_polio,
            dados_transmissoes_recentes.qtde_vacinas_polio_registradas,
            dados_transmissoes_recentes.quantidade_polio_validas,
            dados_transmissoes_recentes.idade_meses_1dose_polio,
            dados_transmissoes_recentes.idade_meses_2dose_polio,
            dados_transmissoes_recentes.idade_meses_3dose_polio,
            dados_transmissoes_recentes.prazo_1dose_polio,
            dados_transmissoes_recentes.prazo_limite_1dose_polio,
            dados_transmissoes_recentes.prazo_2dose_polio,
            dados_transmissoes_recentes.prazo_3dose_polio,
            dados_transmissoes_recentes.data_1dose_penta,
            dados_transmissoes_recentes.data_2dose_penta,
            dados_transmissoes_recentes.data_3dose_penta,
            dados_transmissoes_recentes.qtde_vacinas_penta_registradas,
            dados_transmissoes_recentes.quantidade_penta_validas,
            dados_transmissoes_recentes.idade_meses_1dose_penta,
            dados_transmissoes_recentes.idade_meses_2dose_penta,
            dados_transmissoes_recentes.idade_meses_3dose_penta,
            dados_transmissoes_recentes.prazo_1dose_penta,
            dados_transmissoes_recentes.prazo_limite_1dose_penta,
            dados_transmissoes_recentes.prazo_2dose_penta,
            dados_transmissoes_recentes.prazo_3dose_penta,
            dados_transmissoes_recentes.cidadao_nome_responsavel,
            dados_transmissoes_recentes.estabelecimento_cnes_atendimento,
            dados_transmissoes_recentes.estabelecimento_cnes_cadastro,
            dados_transmissoes_recentes.estabelecimento_nome_atendimento,
            dados_transmissoes_recentes.estabelecimento_nome_cadastro,
            dados_transmissoes_recentes.equipe_ine_atendimento,
            dados_transmissoes_recentes.equipe_ine_cadastro,
            dados_transmissoes_recentes.equipe_nome_atendimento,
            dados_transmissoes_recentes.equipe_nome_cadastro,
            dados_transmissoes_recentes.acs_nome_cadastro,
            dados_transmissoes_recentes.acs_nome_visita,
            dados_transmissoes_recentes.data_ultimo_cadastro_individual,
            dados_transmissoes_recentes.data_ultimo_atendimento_individual,
            dados_transmissoes_recentes.data_ultima_vista_domiciliar,
            dados_transmissoes_recentes.criacao_data,
            dados_transmissoes_recentes.municipio_id_sus,
            dados_transmissoes_recentes.quadrimestre_atual
           FROM dados_transmissoes_recentes
        ), data_registro_producao AS ( -- Seleciona data de produção mais recente com base nas datas de registro das vacinas polio e penta
         SELECT une_as_bases.municipio_id_sus,
            impulso_previne_dados_nominais.equipe_ine(une_as_bases.municipio_id_sus::text, COALESCE(une_as_bases.equipe_ine_cadastro,une_as_bases.equipe_ine_atendimento))::text AS equipe_ine,
            max(GREATEST(une_as_bases.data_1dose_polio, une_as_bases.data_2dose_polio, une_as_bases.data_3dose_polio, une_as_bases.data_1dose_penta, une_as_bases.data_2dose_penta, une_as_bases.data_3dose_penta)) AS dt_registro_producao_mais_recente,
            min(LEAST(une_as_bases.data_1dose_polio, une_as_bases.data_2dose_polio, une_as_bases.data_3dose_polio, une_as_bases.data_1dose_penta, une_as_bases.data_2dose_penta, une_as_bases.data_3dose_penta)) AS dt_registro_producao_mais_antigo
           FROM une_as_bases
          GROUP BY une_as_bases.municipio_id_sus, (impulso_previne_dados_nominais.equipe_ine(une_as_bases.municipio_id_sus::text, COALESCE( une_as_bases.equipe_ine_cadastro,une_as_bases.equipe_ine_atendimento)::text))
        ), tabela_aux AS ( 
         SELECT tb1.municipio_id_sus,
            tb1.cidadao_nome,
            COALESCE(tb1.cidadao_nome_responsavel, 'RESPONSÁVEL NÃO IDENTIFICADO'::character varying) AS cidadao_nome_responsavel,
            (tb1.cidadao_nome || tb1.municipio_id_sus::text) || tb1.dt_nascimento AS chave_cidadao,
            COALESCE(tb1.cidadao_cpf, tb1.dt_nascimento::text::character varying::text) AS cidadao_cpf_dt_nascimento,
            tb1.cidadao_idade_meses_atual AS cidadao_idade_meses,
            tb1.quadrimestre_completa_1_ano,
            tb1.quadrimestre_atual,
                CASE
                    WHEN split_part(tb1.quadrimestre_atual, '.'::text, 2) = 'Q1'::text AND split_part(tb1.quadrimestre_atual, '.'::text, 1) = date_part('year'::text, CURRENT_DATE)::text THEN concat(date_part('year'::text, CURRENT_DATE), '.Q2') --Se o quadri atual for Q1 e se o ano do quadri atual for igual ao ano da data atual, então o quadri futuro será 'ano_atual.Q2'
                    WHEN split_part(tb1.quadrimestre_atual, '.'::text, 2) = 'Q2'::text AND split_part(tb1.quadrimestre_atual, '.'::text, 1) = date_part('year'::text, CURRENT_DATE)::text THEN concat(date_part('year'::text, CURRENT_DATE), '.Q3') --Se o quadri atual for Q2 e se o ano do quadri atual for igual ao ano da data atual, então o quadri futuro será 'ano_atual.Q3'
                    WHEN split_part(tb1.quadrimestre_atual, '.'::text, 1) = date_part('year'::text, CURRENT_DATE)::text AND split_part(tb1.quadrimestre_atual, '.'::text, 2) = 'Q3'::text THEN concat(date_part('year'::text, CURRENT_DATE) + 1::double precision, '.Q1') --Se o quadri atual for Q3 então o quadri futuro será '(ano_atual + 1).Q2'
                    ELSE NULL::text
                END AS quadrimestre_futuro,
            tb1.data_1dose_polio,
            tb1.data_2dose_polio,
            tb1.data_3dose_polio,
            tb1.data_1dose_penta,
            tb1.data_2dose_penta,
            tb1.data_3dose_penta,
            tb1.idade_meses_1dose_polio,
            tb1.idade_meses_2dose_polio,
            tb1.idade_meses_3dose_polio,
            tb1.prazo_1dose_polio,
            tb1.prazo_limite_1dose_polio,
            tb1.prazo_2dose_polio,
            tb1.prazo_3dose_polio,
            tb1.prazo_1dose_penta,
            tb1.prazo_2dose_penta,
            tb1.prazo_3dose_penta,
            COALESCE(tb1.data_1dose_polio, tb1.prazo_1dose_polio) AS data_ou_prazo_1dose_polio,
            COALESCE(tb1.data_2dose_polio, tb1.prazo_2dose_polio) AS data_ou_prazo_2dose_polio,
            COALESCE(tb1.data_3dose_polio, tb1.prazo_3dose_polio) AS data_ou_prazo_3dose_polio,
                CASE
                    WHEN tb1.data_1dose_polio IS NOT NULL AND tb1.data_2dose_polio IS NOT NULL AND tb1.data_3dose_polio IS NOT NULL THEN 1 -- Esquema completo: Caso todos os campos que registram a data de aplicação das vacinas estejam preenchidos.
                    WHEN tb1.data_1dose_polio IS NOT NULL AND tb1.prazo_2dose_polio >= CURRENT_DATE AND tb1.prazo_3dose_polio >= CURRENT_DATE THEN 2 -- Em andamento: Se a D1 não for nula (dose aplicada) e o prazo_D2 e prazo_D3 estiverem no futuro
                    WHEN tb1.data_1dose_polio IS NOT NULL AND tb1.data_2dose_polio IS NOT NULL AND tb1.prazo_3dose_polio >= CURRENT_DATE THEN 2 -- Em andamento: Se a D1 e D2 não forem nulas (ambas doses aplicadas) e o prazo_D3 estiver no futuro
                    when (tb1.prazo_1dose_polio < CURRENT_DATE OR tb1.prazo_2dose_polio < CURRENT_DATE OR tb1.prazo_3dose_polio < CURRENT_DATE) then 3 -- Em atraso: Se algum prazo estiver no passado
                    WHEN tb1.data_1dose_polio IS NULL AND tb1.data_2dose_polio IS NULL AND tb1.data_3dose_polio IS NULL AND tb1.prazo_1dose_polio >= CURRENT_DATE AND tb1.prazo_2dose_polio >= CURRENT_DATE AND tb1.prazo_3dose_polio >= CURRENT_DATE THEN 4 --Não iniciado: Caso nenhum dos campos que registre a data de aplicação esteja preenchido E todos os campos de aprazamento sejam maiores que a data de hoje (futuro)
                    ELSE NULL::integer
                END AS id_status_polio,
            COALESCE(tb1.data_1dose_penta, tb1.prazo_1dose_penta) AS data_ou_prazo_1dose_penta,
            COALESCE(tb1.data_2dose_penta, tb1.prazo_2dose_penta) AS data_ou_prazo_2dose_penta,
            COALESCE(tb1.data_3dose_penta, tb1.prazo_3dose_penta) AS data_ou_prazo_3dose_penta,
                CASE
                    WHEN tb1.data_1dose_penta IS NOT NULL AND tb1.data_2dose_penta IS NOT NULL AND tb1.data_3dose_penta IS NOT NULL THEN 1 -- Esquema completo: Caso todos os campos que registram a data de aplicação das vacinas estejam preenchidos.
                    WHEN tb1.data_1dose_penta IS NOT NULL AND tb1.prazo_2dose_penta >= CURRENT_DATE AND tb1.prazo_3dose_penta >= CURRENT_DATE THEN 2 -- Em andamento: Se a D1 não for nula (dose aplicada) e o prazo_D2 e prazo_D3 estiverem no futuro
                    WHEN tb1.data_1dose_penta IS NOT NULL AND tb1.data_2dose_penta IS NOT NULL AND tb1.prazo_3dose_penta >= CURRENT_DATE THEN 2 -- Em andamento: Se a D1 e D2 não forem nulas (ambas doses aplicadas) e o prazo_D3 estiver no futuro
                    when (tb1.prazo_1dose_penta < CURRENT_DATE OR tb1.prazo_2dose_penta < CURRENT_DATE OR tb1.prazo_3dose_penta < CURRENT_DATE) then 3 -- Em atraso: Se algum prazo estiver no passado
                    WHEN tb1.data_1dose_penta IS NULL AND tb1.data_2dose_penta IS NULL AND tb1.data_3dose_penta IS NULL AND tb1.prazo_1dose_penta >= CURRENT_DATE AND tb1.prazo_2dose_penta >= CURRENT_DATE AND tb1.prazo_3dose_penta >= CURRENT_DATE THEN 4 --Não iniciado: Caso nenhum dos campos que registre a data de aplicação esteja preenchido E todos os campos de aprazamento sejam maiores que a data de hoje (futuro)
                    ELSE NULL::integer
                END AS id_status_penta,
            coalesce(tb1.acs_nome_cadastro, tb1.acs_nome_visita) AS acs_nome,
            impulso_previne_dados_nominais.equipe_ine(tb1.municipio_id_sus::text, COALESCE(tb1.equipe_ine_cadastro, tb1.equipe_ine_atendimento)::text) AS equipe_ine,
            COALESCE(tb1.equipe_nome_cadastro, tb1.equipe_nome_atendimento, 'SEM EQUIPE'::character varying) AS equipe_nome,
            CURRENT_DATE AS atualizacao_data,
            tb1.criacao_data::date AS criacao_data
           FROM une_as_bases tb1
        ), cores AS (
         SELECT tb_1.municipio_id_sus,
            tb_1.cidadao_nome,
            tb_1.chave_cidadao,
            tb_1.cidadao_idade_meses,
            tb_1.data_1dose_polio,
            tb_1.data_2dose_polio,
            tb_1.data_3dose_polio,
            tb_1.prazo_1dose_polio,
            tb_1.prazo_2dose_polio,
            tb_1.prazo_3dose_polio,
            tb_1.id_status_polio,
            tb_1.data_ou_prazo_1dose_polio,
                CASE
                    WHEN tb_1.data_ou_prazo_1dose_polio = tb_1.data_1dose_polio THEN 2 --quando a data de aplicação registrada for igual ao data_ou_prazo = verde
                    WHEN tb_1.id_status_polio = 4 AND tb_1.data_ou_prazo_1dose_polio >= CURRENT_DATE THEN 1 --quando o status for "não iniciado" e prazo estiver no futuro = cinza
                    WHEN tb_1.id_status_polio = 3 AND tb_1.data_ou_prazo_1dose_polio < CURRENT_DATE OR tb_1.data_1dose_polio IS NULL AND tb_1.data_ou_prazo_1dose_polio < CURRENT_DATE THEN 3 -- quando o status for "em atraso" e prazo estiver no passado, ou se a data de aplicação for nula
                    ELSE NULL::integer
                END AS id_cor_1dose_polio,
            tb_1.data_ou_prazo_2dose_polio,
                CASE
                    WHEN tb_1.data_ou_prazo_2dose_polio = tb_1.data_2dose_polio THEN 2 --quando a data de aplicação registrada for igual ao data_ou_prazo = verde
                    WHEN tb_1.id_status_polio = 4 AND tb_1.data_ou_prazo_2dose_polio >= CURRENT_DATE THEN 1 --quando o status for "não iniciado" e prazo estiver no futuro = cinza
                    WHEN tb_1.data_2dose_polio IS NULL AND tb_1.data_ou_prazo_2dose_polio >= CURRENT_DATE THEN 1 -- quando a data de aplicação registrada for nula e o prazo estiver no futuro = cinza
                    WHEN tb_1.data_2dose_polio IS NULL AND tb_1.data_ou_prazo_2dose_polio < CURRENT_DATE THEN 3 -- quando a data de aplicação for nula e o prazo estiver no passado = vermelho
                    ELSE NULL::integer
                END AS id_cor_2dose_polio,
            tb_1.data_ou_prazo_3dose_polio,
                CASE
                    WHEN tb_1.data_ou_prazo_3dose_polio = tb_1.data_3dose_polio THEN 2 --quando a data de aplicação registrada for igual ao data_ou_prazo = verde
                    WHEN tb_1.id_status_polio = 4 AND tb_1.data_ou_prazo_3dose_polio >= CURRENT_DATE THEN 1 --quando o status for "não iniciado" e prazo estiver no futuro = cinza
                    WHEN tb_1.data_3dose_polio IS NULL AND tb_1.data_ou_prazo_3dose_polio >= CURRENT_DATE THEN 1 -- quando a data de aplicação registrada for nula e o prazo estiver no futuro = cinza
                    WHEN tb_1.data_3dose_polio IS NULL AND tb_1.data_ou_prazo_3dose_polio < CURRENT_DATE THEN 3 -- quando a data de aplicação for nula e o prazo estiver no passado = vermelho
                    ELSE NULL::integer
                END AS id_cor_3dose_polio,
            tb_1.data_1dose_penta,
            tb_1.data_2dose_penta,
            tb_1.data_3dose_penta,
            tb_1.prazo_1dose_penta,
            tb_1.prazo_2dose_penta,
            tb_1.prazo_3dose_penta,
            tb_1.id_status_penta,
            tb_1.data_ou_prazo_1dose_penta,
                CASE
                    WHEN tb_1.data_ou_prazo_1dose_penta = tb_1.data_1dose_penta THEN 2
                    WHEN tb_1.id_status_penta = 4 AND tb_1.data_ou_prazo_1dose_penta >= CURRENT_DATE THEN 1
                    WHEN tb_1.id_status_penta = 3 AND tb_1.data_ou_prazo_1dose_penta < CURRENT_DATE OR tb_1.data_1dose_penta IS NULL AND tb_1.data_ou_prazo_1dose_penta < CURRENT_DATE THEN 3
                    ELSE NULL::integer
                END AS id_cor_1dose_penta,
            tb_1.data_ou_prazo_2dose_penta,
                CASE
                    WHEN tb_1.data_ou_prazo_2dose_penta = tb_1.data_2dose_penta THEN 2
                    WHEN tb_1.id_status_penta = 4 AND tb_1.data_ou_prazo_2dose_penta >= CURRENT_DATE THEN 1
                    WHEN tb_1.data_2dose_penta IS NULL AND tb_1.data_ou_prazo_2dose_penta >= CURRENT_DATE THEN 1
                    WHEN tb_1.data_2dose_penta IS NULL AND tb_1.data_ou_prazo_2dose_penta < CURRENT_DATE THEN 3
                    ELSE NULL::integer
                END AS id_cor_2dose_penta,
            tb_1.data_ou_prazo_3dose_penta,
                CASE
                    WHEN tb_1.data_ou_prazo_3dose_penta = tb_1.data_3dose_penta THEN 2
                    WHEN tb_1.id_status_penta = 4 AND tb_1.data_ou_prazo_3dose_penta >= CURRENT_DATE THEN 1
                    WHEN tb_1.data_3dose_penta IS NULL AND tb_1.data_ou_prazo_3dose_penta >= CURRENT_DATE THEN 1
                    WHEN tb_1.data_3dose_penta IS NULL AND tb_1.data_ou_prazo_3dose_penta < CURRENT_DATE THEN 3
                    ELSE NULL::integer
                END AS id_cor_3dose_penta
           FROM tabela_aux tb_1
        )
 SELECT tb.municipio_id_sus,
    concat(tb2.nome, ' - ', tb2.uf_sigla) AS municipio_uf,
    tb.cidadao_nome,
    tb.cidadao_nome_responsavel,
    tb.cidadao_cpf_dt_nascimento,
    tb.cidadao_idade_meses,
    tb.quadrimestre_completa_1_ano,
        CASE
            WHEN tb.quadrimestre_completa_1_ano::text = tb.quadrimestre_atual THEN 1 -- quadrimestre atual
            WHEN tb.quadrimestre_completa_1_ano::text = tb.quadrimestre_futuro THEN 2 -- próximo quadrimestre
            ELSE 3 -- quadrimestres futuros
        END AS id_status_quadrimestre,
    tb.data_ou_prazo_1dose_polio,
    tb.data_ou_prazo_2dose_polio,
    tb.data_ou_prazo_3dose_polio,
    tb.id_status_polio,
    c.id_cor_1dose_polio,
    c.id_cor_2dose_polio,
    c.id_cor_3dose_polio,
    tb.data_ou_prazo_1dose_penta,
    tb.data_ou_prazo_2dose_penta,
    tb.data_ou_prazo_3dose_penta,
    tb.id_status_penta,
    c.id_cor_1dose_penta,
    c.id_cor_2dose_penta,
    c.id_cor_3dose_penta,
    tb.acs_nome,
    tb.equipe_ine,
    tb.equipe_nome,
    tb.criacao_data,
    tb.atualizacao_data,
    drp.dt_registro_producao_mais_recente
   FROM tabela_aux tb
     LEFT JOIN data_registro_producao drp ON drp.municipio_id_sus::text = tb.municipio_id_sus::text AND drp.equipe_ine = tb.equipe_ine
     LEFT JOIN cores c ON c.chave_cidadao = tb.chave_cidadao
     LEFT JOIN listas_de_codigos.municipios tb2 ON tb.municipio_id_sus::bpchar = tb2.id_sus
     LEFT JOIN listas_de_codigos.periodos p ON tb.quadrimestre_completa_1_ano::text = p.codigo::text
  WHERE p.data_fim >= CURRENT_DATE
WITH DATA;